import { createRequire } from "module";
const require = createRequire(import.meta.url);
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Plugin to copy styles.css from src to root
const copyStylesPlugin = {
    name: 'copy-styles',
    setup(build) {
        build.onEnd(() => {
            try {
                fs.copyFileSync('src/styles.css', 'styles.css');
                console.log('Copied src/styles.css to styles.css');
            } catch (e) {
                console.error('Failed to copy styles.css:', e);
            }
        });
    },
};

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/closebrackets",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/comment",
        "@codemirror/fold",
        "@codemirror/gutter",
        "@codemirror/highlight",
        "@codemirror/history",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/matchbrackets",
        "@codemirror/panel",
        "@codemirror/rangeset",
        "@codemirror/rectangular-selection",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/stream-parser",
        "@codemirror/text",
        "@codemirror/tooltip",
        "@codemirror/view",
        ...builtins],
    format: "cjs",
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    plugins: [
        copyStylesPlugin,
        {
            name: 'ws-node-resolution',
            setup(build) {
                // Force 'ws' to resolve to index.js instead of browser.js
                // We mark it as NOT external so it gets bundled, but we must use the correct file.
                // Since this runs in node environment for build, we can use require.resolve
                const wsPath = require('path').resolve('node_modules/ws/index.js');
                build.onResolve({ filter: /^ws$/ }, (args) => {
                    return { path: wsPath };
                });
            },
        },
        {
            name: 'y-webrtc-trystero-resolution',
            setup(build) {
                // The git install of @winstonfassett/y-webrtc-trystero has no dist/ dir,
                // so resolve to the source file directly
                const srcPath = require('path').resolve('node_modules/@winstonfassett/y-webrtc-trystero/src/y-webrtc-trystero.js');
                build.onResolve({ filter: /^@winstonfassett\/y-webrtc-trystero$/ }, () => {
                    return { path: srcPath };
                });
            },
        }
    ],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
